CREATE TABLE USERS (
	USER_ID SERIAL PRIMARY KEY,
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	NAME VARCHAR(100) NOT NULL
);

CREATE TABLE CATEGORIES (
	CATEGORY_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL
);

CREATE TABLE GROUPS (
	GROUP_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL
);

CREATE TABLE GROUP_MEMBERS (
	GROUP_ID INT REFERENCES GROUPS (GROUP_ID) ON DELETE CASCADE,
	USER_ID INT REFERENCES USERS (USER_ID) ON DELETE CASCADE,
	JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	PRIMARY KEY (GROUP_ID, USER_ID)
);

CREATE TABLE EXPENSES (
	EXPENSE_ID SERIAL PRIMARY KEY,
	USER_ID INT REFERENCES USERS (USER_ID) ON DELETE CASCADE,
	CATEGORY_ID INT REFERENCES CATEGORIES (CATEGORY_ID) ON DELETE SET NULL,
	GROUP_ID INT REFERENCES GROUPS (GROUP_ID) ON DELETE SET NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	OBSERVATION TEXT,
	AMOUNT DECIMAL(10, 2) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);